INSERT INTO m_provinsi (id, nama) VALUES (11, 'ACEH');
INSERT INTO m_provinsi (id, nama) VALUES (12, 'SUMATERA UTARA');
INSERT INTO m_provinsi (id, nama) VALUES (13, 'SUMATERA BARAT');
INSERT INTO m_provinsi (id, nama) VALUES (14, 'RIAU');
INSERT INTO m_provinsi (id, nama) VALUES (15, 'JAMBI');
INSERT INTO m_provinsi (id, nama) VALUES (16, 'SUMATERA SELATAN');
INSERT INTO m_provinsi (id, nama) VALUES (17, 'BENGKULU');
INSERT INTO m_provinsi (id, nama) VALUES (18, 'LAMPUNG');
INSERT INTO m_provinsi (id, nama) VALUES (19, 'KEPULAUAN BANGKA BELITUNG');
INSERT INTO m_provinsi (id, nama) VALUES (21, 'KEPULAUAN RIAU');
INSERT INTO m_provinsi (id, nama) VALUES (31, 'DKI JAKARTA');
INSERT INTO m_provinsi (id, nama) VALUES (32, 'JAWA BARAT');
INSERT INTO m_provinsi (id, nama) VALUES (33, 'JAWA TENGAH');
INSERT INTO m_provinsi (id, nama) VALUES (34, 'DI YOGYAKARTA');
INSERT INTO m_provinsi (id, nama) VALUES (35, 'JAWA TIMUR');
INSERT INTO m_provinsi (id, nama) VALUES (36, 'BANTEN');
INSERT INTO m_provinsi (id, nama) VALUES (51, 'BALI');
INSERT INTO m_provinsi (id, nama) VALUES (52, 'NUSA TENGGARA BARAT');
INSERT INTO m_provinsi (id, nama) VALUES (53, 'NUSA TENGGARA TIMUR');
INSERT INTO m_provinsi (id, nama) VALUES (61, 'KALIMANTAN BARAT');
INSERT INTO m_provinsi (id, nama) VALUES (62, 'KALIMANTAN TENGAH');
INSERT INTO m_provinsi (id, nama) VALUES (63, 'KALIMANTAN SELATAN');
INSERT INTO m_provinsi (id, nama) VALUES (64, 'KALIMANTAN TIMUR');
INSERT INTO m_provinsi (id, nama) VALUES (65, 'KALIMANTAN UTARA');
INSERT INTO m_provinsi (id, nama) VALUES (71, 'SULAWESI UTARA');
INSERT INTO m_provinsi (id, nama) VALUES (72, 'SULAWESI TENGAH');
INSERT INTO m_provinsi (id, nama) VALUES (73, 'SULAWESI SELATAN');
INSERT INTO m_provinsi (id, nama) VALUES (74, 'SULAWESI TENGGARA');
INSERT INTO m_provinsi (id, nama) VALUES (75, 'GORONTALO');
INSERT INTO m_provinsi (id, nama) VALUES (76, 'SULAWESI BARAT');
INSERT INTO m_provinsi (id, nama) VALUES (81, 'MALUKU');
INSERT INTO m_provinsi (id, nama) VALUES (82, 'MALUKU UTARA');
INSERT INTO m_provinsi (id, nama) VALUES (91, 'PAPUA BARAT');
INSERT INTO m_provinsi (id, nama) VALUES (94, 'PAPUA');