INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1101, 11, 'KABUPATEN SIMEULUE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1102, 11, 'KABUPATEN ACEH SINGKIL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1103, 11, 'KABUPATEN ACEH SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1104, 11, 'KABUPATEN ACEH TENGGARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1105, 11, 'KABUPATEN ACEH TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1106, 11, 'KABUPATEN ACEH TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1107, 11, 'KABUPATEN ACEH BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1108, 11, 'KABUPATEN ACEH BESAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1109, 11, 'KABUPATEN PIDIE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1110, 11, 'KABUPATEN BIREUEN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1111, 11, 'KABUPATEN ACEH UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1112, 11, 'KABUPATEN ACEH BARAT DAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1113, 11, 'KABUPATEN GAYO LUES');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1114, 11, 'KABUPATEN ACEH TAMIANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1115, 11, 'KABUPATEN NAGAN RAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1116, 11, 'KABUPATEN ACEH JAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1117, 11, 'KABUPATEN BENER MERIAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1118, 11, 'KABUPATEN PIDIE JAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1171, 11, 'KOTA BANDA ACEH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1172, 11, 'KOTA SABANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1173, 11, 'KOTA LANGSA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1174, 11, 'KOTA LHOKSEUMAWE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1175, 11, 'KOTA SUBULUSSALAM');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1201, 12, 'KABUPATEN NIAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1202, 12, 'KABUPATEN MANDAILING NATAL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1203, 12, 'KABUPATEN TAPANULI SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1204, 12, 'KABUPATEN TAPANULI TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1205, 12, 'KABUPATEN TAPANULI UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1206, 12, 'KABUPATEN TOBA SAMOSIR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1207, 12, 'KABUPATEN LABUHAN BATU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1208, 12, 'KABUPATEN ASAHAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1209, 12, 'KABUPATEN SIMALUNGUN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1210, 12, 'KABUPATEN DAIRI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1211, 12, 'KABUPATEN KARO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1212, 12, 'KABUPATEN DELI SERDANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1213, 12, 'KABUPATEN LANGKAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1214, 12, 'KABUPATEN NIAS SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1215, 12, 'KABUPATEN HUMBANG HASUNDUTAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1216, 12, 'KABUPATEN PAKPAK BHARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1217, 12, 'KABUPATEN SAMOSIR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1218, 12, 'KABUPATEN SERDANG BEDAGAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1219, 12, 'KABUPATEN BATU BARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1220, 12, 'KABUPATEN PADANG LAWAS UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1221, 12, 'KABUPATEN PADANG LAWAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1222, 12, 'KABUPATEN LABUHAN BATU SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1223, 12, 'KABUPATEN LABUHAN BATU UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1224, 12, 'KABUPATEN NIAS UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1225, 12, 'KABUPATEN NIAS BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1271, 12, 'KOTA SIBOLGA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1272, 12, 'KOTA TANJUNG BALAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1273, 12, 'KOTA PEMATANG SIANTAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1274, 12, 'KOTA TEBING TINGGI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1275, 12, 'KOTA MEDAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1276, 12, 'KOTA BINJAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1277, 12, 'KOTA PADANGSIDIMPUAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1278, 12, 'KOTA GUNUNGSITOLI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1301, 13, 'KABUPATEN KEPULAUAN MENTAWAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1302, 13, 'KABUPATEN PESISIR SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1303, 13, 'KABUPATEN SOLOK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1304, 13, 'KABUPATEN SIJUNJUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1305, 13, 'KABUPATEN TANAH DATAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1306, 13, 'KABUPATEN PADANG PARIAMAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1307, 13, 'KABUPATEN AGAM');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1308, 13, 'KABUPATEN LIMA PULUH KOTA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1309, 13, 'KABUPATEN PASAMAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1310, 13, 'KABUPATEN SOLOK SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1311, 13, 'KABUPATEN DHARMASRAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1312, 13, 'KABUPATEN PASAMAN BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1371, 13, 'KOTA PADANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1372, 13, 'KOTA SOLOK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1373, 13, 'KOTA SAWAH LUNTO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1374, 13, 'KOTA PADANG PANJANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1375, 13, 'KOTA BUKITTINGGI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1376, 13, 'KOTA PAYAKUMBUH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1377, 13, 'KOTA PARIAMAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1401, 14, 'KABUPATEN KUANTAN SINGINGI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1402, 14, 'KABUPATEN INDRAGIRI HULU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1403, 14, 'KABUPATEN INDRAGIRI HILIR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1404, 14, 'KABUPATEN PELALAWAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1405, 14, 'KABUPATEN S I A K');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1406, 14, 'KABUPATEN KAMPAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1407, 14, 'KABUPATEN ROKAN HULU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1408, 14, 'KABUPATEN BENGKALIS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1409, 14, 'KABUPATEN ROKAN HILIR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1410, 14, 'KABUPATEN KEPULAUAN MERANTI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1471, 14, 'KOTA PEKANBARU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1473, 14, 'KOTA D U M A I');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1501, 15, 'KABUPATEN KERINCI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1502, 15, 'KABUPATEN MERANGIN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1503, 15, 'KABUPATEN SAROLANGUN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1504, 15, 'KABUPATEN BATANG HARI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1505, 15, 'KABUPATEN MUARO JAMBI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1506, 15, 'KABUPATEN TANJUNG JABUNG TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1507, 15, 'KABUPATEN TANJUNG JABUNG BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1508, 15, 'KABUPATEN TEBO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1509, 15, 'KABUPATEN BUNGO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1571, 15, 'KOTA JAMBI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1572, 15, 'KOTA SUNGAI PENUH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1601, 16, 'KABUPATEN OGAN KOMERING ULU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1602, 16, 'KABUPATEN OGAN KOMERING ILIR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1603, 16, 'KABUPATEN MUARA ENIM');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1604, 16, 'KABUPATEN LAHAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1605, 16, 'KABUPATEN MUSI RAWAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1606, 16, 'KABUPATEN MUSI BANYUASIN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1607, 16, 'KABUPATEN BANYU ASIN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1608, 16, 'KABUPATEN OGAN KOMERING ULU SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1609, 16, 'KABUPATEN OGAN KOMERING ULU TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1610, 16, 'KABUPATEN OGAN ILIR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1611, 16, 'KABUPATEN EMPAT LAWANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1612, 16, 'KABUPATEN PENUKAL ABAB LEMATANG ILIR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1613, 16, 'KABUPATEN MUSI RAWAS UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1671, 16, 'KOTA PALEMBANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1672, 16, 'KOTA PRABUMULIH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1673, 16, 'KOTA PAGAR ALAM');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1674, 16, 'KOTA LUBUKLINGGAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1701, 17, 'KABUPATEN BENGKULU SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1702, 17, 'KABUPATEN REJANG LEBONG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1703, 17, 'KABUPATEN BENGKULU UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1704, 17, 'KABUPATEN KAUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1705, 17, 'KABUPATEN SELUMA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1706, 17, 'KABUPATEN MUKOMUKO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1707, 17, 'KABUPATEN LEBONG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1708, 17, 'KABUPATEN KEPAHIANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1709, 17, 'KABUPATEN BENGKULU TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1771, 17, 'KOTA BENGKULU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1801, 18, 'KABUPATEN LAMPUNG BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1802, 18, 'KABUPATEN TANGGAMUS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1803, 18, 'KABUPATEN LAMPUNG SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1804, 18, 'KABUPATEN LAMPUNG TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1805, 18, 'KABUPATEN LAMPUNG TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1806, 18, 'KABUPATEN LAMPUNG UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1807, 18, 'KABUPATEN WAY KANAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1808, 18, 'KABUPATEN TULANGBAWANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1809, 18, 'KABUPATEN PESAWARAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1810, 18, 'KABUPATEN PRINGSEWU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1811, 18, 'KABUPATEN MESUJI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1812, 18, 'KABUPATEN TULANG BAWANG BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1813, 18, 'KABUPATEN PESISIR BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1871, 18, 'KOTA BANDAR LAMPUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1872, 18, 'KOTA METRO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1901, 19, 'KABUPATEN BANGKA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1902, 19, 'KABUPATEN BELITUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1903, 19, 'KABUPATEN BANGKA BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1904, 19, 'KABUPATEN BANGKA TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1905, 19, 'KABUPATEN BANGKA SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1906, 19, 'KABUPATEN BELITUNG TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (1971, 19, 'KOTA PANGKAL PINANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (2101, 21, 'KABUPATEN KARIMUN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (2102, 21, 'KABUPATEN BINTAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (2103, 21, 'KABUPATEN NATUNA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (2104, 21, 'KABUPATEN LINGGA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (2105, 21, 'KABUPATEN KEPULAUAN ANAMBAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (2171, 21, 'KOTA B A T A M');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (2172, 21, 'KOTA TANJUNG PINANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3101, 31, 'KABUPATEN KEPULAUAN SERIBU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3171, 31, 'KOTA JAKARTA SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3172, 31, 'KOTA JAKARTA TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3173, 31, 'KOTA JAKARTA PUSAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3174, 31, 'KOTA JAKARTA BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3175, 31, 'KOTA JAKARTA UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3201, 32, 'KABUPATEN BOGOR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3202, 32, 'KABUPATEN SUKABUMI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3203, 32, 'KABUPATEN CIANJUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3204, 32, 'KABUPATEN BANDUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3205, 32, 'KABUPATEN GARUT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3206, 32, 'KABUPATEN TASIKMALAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3207, 32, 'KABUPATEN CIAMIS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3208, 32, 'KABUPATEN KUNINGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3209, 32, 'KABUPATEN CIREBON');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3210, 32, 'KABUPATEN MAJALENGKA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3211, 32, 'KABUPATEN SUMEDANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3212, 32, 'KABUPATEN INDRAMAYU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3213, 32, 'KABUPATEN SUBANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3214, 32, 'KABUPATEN PURWAKARTA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3215, 32, 'KABUPATEN KARAWANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3216, 32, 'KABUPATEN BEKASI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3217, 32, 'KABUPATEN BANDUNG BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3218, 32, 'KABUPATEN PANGANDARAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3271, 32, 'KOTA BOGOR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3272, 32, 'KOTA SUKABUMI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3273, 32, 'KOTA BANDUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3274, 32, 'KOTA CIREBON');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3275, 32, 'KOTA BEKASI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3276, 32, 'KOTA DEPOK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3277, 32, 'KOTA CIMAHI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3278, 32, 'KOTA TASIKMALAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3279, 32, 'KOTA BANJAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3301, 33, 'KABUPATEN CILACAP');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3302, 33, 'KABUPATEN BANYUMAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3303, 33, 'KABUPATEN PURBALINGGA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3304, 33, 'KABUPATEN BANJARNEGARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3305, 33, 'KABUPATEN KEBUMEN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3306, 33, 'KABUPATEN PURWOREJO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3307, 33, 'KABUPATEN WONOSOBO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3308, 33, 'KABUPATEN MAGELANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3309, 33, 'KABUPATEN BOYOLALI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3310, 33, 'KABUPATEN KLATEN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3311, 33, 'KABUPATEN SUKOHARJO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3312, 33, 'KABUPATEN WONOGIRI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3313, 33, 'KABUPATEN KARANGANYAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3314, 33, 'KABUPATEN SRAGEN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3315, 33, 'KABUPATEN GROBOGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3316, 33, 'KABUPATEN BLORA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3317, 33, 'KABUPATEN REMBANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3318, 33, 'KABUPATEN PATI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3319, 33, 'KABUPATEN KUDUS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3320, 33, 'KABUPATEN JEPARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3321, 33, 'KABUPATEN DEMAK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3322, 33, 'KABUPATEN SEMARANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3323, 33, 'KABUPATEN TEMANGGUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3324, 33, 'KABUPATEN KENDAL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3325, 33, 'KABUPATEN BATANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3326, 33, 'KABUPATEN PEKALONGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3327, 33, 'KABUPATEN PEMALANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3328, 33, 'KABUPATEN TEGAL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3329, 33, 'KABUPATEN BREBES');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3371, 33, 'KOTA MAGELANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3372, 33, 'KOTA SURAKARTA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3373, 33, 'KOTA SALATIGA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3374, 33, 'KOTA SEMARANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3375, 33, 'KOTA PEKALONGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3376, 33, 'KOTA TEGAL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3401, 34, 'KABUPATEN KULON PROGO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3402, 34, 'KABUPATEN BANTUL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3403, 34, 'KABUPATEN GUNUNG KIDUL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3404, 34, 'KABUPATEN SLEMAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3471, 34, 'KOTA YOGYAKARTA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3501, 35, 'KABUPATEN PACITAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3502, 35, 'KABUPATEN PONOROGO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3503, 35, 'KABUPATEN TRENGGALEK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3504, 35, 'KABUPATEN TULUNGAGUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3505, 35, 'KABUPATEN BLITAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3506, 35, 'KABUPATEN KEDIRI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3507, 35, 'KABUPATEN MALANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3508, 35, 'KABUPATEN LUMAJANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3509, 35, 'KABUPATEN JEMBER');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3510, 35, 'KABUPATEN BANYUWANGI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3511, 35, 'KABUPATEN BONDOWOSO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3512, 35, 'KABUPATEN SITUBONDO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3513, 35, 'KABUPATEN PROBOLINGGO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3514, 35, 'KABUPATEN PASURUAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3515, 35, 'KABUPATEN SIDOARJO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3516, 35, 'KABUPATEN MOJOKERTO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3517, 35, 'KABUPATEN JOMBANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3518, 35, 'KABUPATEN NGANJUK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3519, 35, 'KABUPATEN MADIUN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3520, 35, 'KABUPATEN MAGETAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3521, 35, 'KABUPATEN NGAWI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3522, 35, 'KABUPATEN BOJONEGORO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3523, 35, 'KABUPATEN TUBAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3524, 35, 'KABUPATEN LAMONGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3525, 35, 'KABUPATEN GRESIK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3526, 35, 'KABUPATEN BANGKALAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3527, 35, 'KABUPATEN SAMPANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3528, 35, 'KABUPATEN PAMEKASAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3529, 35, 'KABUPATEN SUMENEP');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3571, 35, 'KOTA KEDIRI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3572, 35, 'KOTA BLITAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3573, 35, 'KOTA MALANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3574, 35, 'KOTA PROBOLINGGO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3575, 35, 'KOTA PASURUAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3576, 35, 'KOTA MOJOKERTO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3577, 35, 'KOTA MADIUN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3578, 35, 'KOTA SURABAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3579, 35, 'KOTA BATU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3601, 36, 'KABUPATEN PANDEGLANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3602, 36, 'KABUPATEN LEBAK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3603, 36, 'KABUPATEN TANGERANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3604, 36, 'KABUPATEN SERANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3671, 36, 'KOTA TANGERANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3672, 36, 'KOTA CILEGON');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3673, 36, 'KOTA SERANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (3674, 36, 'KOTA TANGERANG SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5101, 51, 'KABUPATEN JEMBRANA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5102, 51, 'KABUPATEN TABANAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5103, 51, 'KABUPATEN BADUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5104, 51, 'KABUPATEN GIANYAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5105, 51, 'KABUPATEN KLUNGKUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5106, 51, 'KABUPATEN BANGLI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5107, 51, 'KABUPATEN KARANG ASEM');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5108, 51, 'KABUPATEN BULELENG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5171, 51, 'KOTA DENPASAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5201, 52, 'KABUPATEN LOMBOK BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5202, 52, 'KABUPATEN LOMBOK TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5203, 52, 'KABUPATEN LOMBOK TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5204, 52, 'KABUPATEN SUMBAWA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5205, 52, 'KABUPATEN DOMPU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5206, 52, 'KABUPATEN BIMA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5207, 52, 'KABUPATEN SUMBAWA BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5208, 52, 'KABUPATEN LOMBOK UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5271, 52, 'KOTA MATARAM');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5272, 52, 'KOTA BIMA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5301, 53, 'KABUPATEN SUMBA BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5302, 53, 'KABUPATEN SUMBA TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5303, 53, 'KABUPATEN KUPANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5304, 53, 'KABUPATEN TIMOR TENGAH SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5305, 53, 'KABUPATEN TIMOR TENGAH UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5306, 53, 'KABUPATEN BELU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5307, 53, 'KABUPATEN ALOR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5308, 53, 'KABUPATEN LEMBATA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5309, 53, 'KABUPATEN FLORES TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5310, 53, 'KABUPATEN SIKKA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5311, 53, 'KABUPATEN ENDE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5312, 53, 'KABUPATEN NGADA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5313, 53, 'KABUPATEN MANGGARAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5314, 53, 'KABUPATEN ROTE NDAO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5315, 53, 'KABUPATEN MANGGARAI BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5316, 53, 'KABUPATEN SUMBA TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5317, 53, 'KABUPATEN SUMBA BARAT DAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5318, 53, 'KABUPATEN NAGEKEO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5319, 53, 'KABUPATEN MANGGARAI TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5320, 53, 'KABUPATEN SABU RAIJUA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5321, 53, 'KABUPATEN MALAKA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (5371, 53, 'KOTA KUPANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6101, 61, 'KABUPATEN SAMBAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6102, 61, 'KABUPATEN BENGKAYANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6103, 61, 'KABUPATEN LANDAK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6104, 61, 'KABUPATEN MEMPAWAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6105, 61, 'KABUPATEN SANGGAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6106, 61, 'KABUPATEN KETAPANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6107, 61, 'KABUPATEN SINTANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6108, 61, 'KABUPATEN KAPUAS HULU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6109, 61, 'KABUPATEN SEKADAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6110, 61, 'KABUPATEN MELAWI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6111, 61, 'KABUPATEN KAYONG UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6112, 61, 'KABUPATEN KUBU RAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6171, 61, 'KOTA PONTIANAK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6172, 61, 'KOTA SINGKAWANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6201, 62, 'KABUPATEN KOTAWARINGIN BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6202, 62, 'KABUPATEN KOTAWARINGIN TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6203, 62, 'KABUPATEN KAPUAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6204, 62, 'KABUPATEN BARITO SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6205, 62, 'KABUPATEN BARITO UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6206, 62, 'KABUPATEN SUKAMARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6207, 62, 'KABUPATEN LAMANDAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6208, 62, 'KABUPATEN SERUYAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6209, 62, 'KABUPATEN KATINGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6210, 62, 'KABUPATEN PULANG PISAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6211, 62, 'KABUPATEN GUNUNG MAS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6212, 62, 'KABUPATEN BARITO TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6213, 62, 'KABUPATEN MURUNG RAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6271, 62, 'KOTA PALANGKA RAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6301, 63, 'KABUPATEN TANAH LAUT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6302, 63, 'KABUPATEN KOTA BARU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6303, 63, 'KABUPATEN BANJAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6304, 63, 'KABUPATEN BARITO KUALA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6305, 63, 'KABUPATEN TAPIN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6306, 63, 'KABUPATEN HULU SUNGAI SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6307, 63, 'KABUPATEN HULU SUNGAI TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6308, 63, 'KABUPATEN HULU SUNGAI UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6309, 63, 'KABUPATEN TABALONG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6310, 63, 'KABUPATEN TANAH BUMBU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6311, 63, 'KABUPATEN BALANGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6371, 63, 'KOTA BANJARMASIN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6372, 63, 'KOTA BANJAR BARU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6401, 64, 'KABUPATEN PASER');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6402, 64, 'KABUPATEN KUTAI BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6403, 64, 'KABUPATEN KUTAI KARTANEGARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6404, 64, 'KABUPATEN KUTAI TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6405, 64, 'KABUPATEN BERAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6409, 64, 'KABUPATEN PENAJAM PASER UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6411, 64, 'KABUPATEN MAHAKAM HULU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6471, 64, 'KOTA BALIKPAPAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6472, 64, 'KOTA SAMARINDA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6474, 64, 'KOTA BONTANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6501, 65, 'KABUPATEN MALINAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6502, 65, 'KABUPATEN BULUNGAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6503, 65, 'KABUPATEN TANA TIDUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6504, 65, 'KABUPATEN NUNUKAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (6571, 65, 'KOTA TARAKAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7101, 71, 'KABUPATEN BOLAANG MONGONDOW');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7102, 71, 'KABUPATEN MINAHASA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7103, 71, 'KABUPATEN KEPULAUAN SANGIHE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7104, 71, 'KABUPATEN KEPULAUAN TALAUD');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7105, 71, 'KABUPATEN MINAHASA SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7106, 71, 'KABUPATEN MINAHASA UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7107, 71, 'KABUPATEN BOLAANG MONGONDOW UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7108, 71, 'KABUPATEN SIAU TAGULANDANG BIARO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7109, 71, 'KABUPATEN MINAHASA TENGGARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7110, 71, 'KABUPATEN BOLAANG MONGONDOW SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7111, 71, 'KABUPATEN BOLAANG MONGONDOW TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7171, 71, 'KOTA MANADO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7172, 71, 'KOTA BITUNG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7173, 71, 'KOTA TOMOHON');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7174, 71, 'KOTA KOTAMOBAGU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7201, 72, 'KABUPATEN BANGGAI KEPULAUAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7202, 72, 'KABUPATEN BANGGAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7203, 72, 'KABUPATEN MOROWALI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7204, 72, 'KABUPATEN POSO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7205, 72, 'KABUPATEN DONGGALA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7206, 72, 'KABUPATEN TOLI-TOLI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7207, 72, 'KABUPATEN BUOL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7208, 72, 'KABUPATEN PARIGI MOUTONG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7209, 72, 'KABUPATEN TOJO UNA-UNA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7210, 72, 'KABUPATEN SIGI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7211, 72, 'KABUPATEN BANGGAI LAUT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7212, 72, 'KABUPATEN MOROWALI UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7271, 72, 'KOTA PALU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7301, 73, 'KABUPATEN KEPULAUAN SELAYAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7302, 73, 'KABUPATEN BULUKUMBA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7303, 73, 'KABUPATEN BANTAENG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7304, 73, 'KABUPATEN JENEPONTO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7305, 73, 'KABUPATEN TAKALAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7306, 73, 'KABUPATEN GOWA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7307, 73, 'KABUPATEN SINJAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7308, 73, 'KABUPATEN MAROS');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7309, 73, 'KABUPATEN PANGKAJENE DAN KEPULAUAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7310, 73, 'KABUPATEN BARRU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7311, 73, 'KABUPATEN BONE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7312, 73, 'KABUPATEN SOPPENG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7313, 73, 'KABUPATEN WAJO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7314, 73, 'KABUPATEN SIDENRENG RAPPANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7315, 73, 'KABUPATEN PINRANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7316, 73, 'KABUPATEN ENREKANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7317, 73, 'KABUPATEN LUWU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7318, 73, 'KABUPATEN TANA TORAJA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7322, 73, 'KABUPATEN LUWU UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7325, 73, 'KABUPATEN LUWU TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7326, 73, 'KABUPATEN TORAJA UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7371, 73, 'KOTA MAKASSAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7372, 73, 'KOTA PAREPARE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7373, 73, 'KOTA PALOPO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7401, 74, 'KABUPATEN BUTON');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7402, 74, 'KABUPATEN MUNA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7403, 74, 'KABUPATEN KONAWE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7404, 74, 'KABUPATEN KOLAKA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7405, 74, 'KABUPATEN KONAWE SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7406, 74, 'KABUPATEN BOMBANA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7407, 74, 'KABUPATEN WAKATOBI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7408, 74, 'KABUPATEN KOLAKA UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7409, 74, 'KABUPATEN BUTON UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7410, 74, 'KABUPATEN KONAWE UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7411, 74, 'KABUPATEN KOLAKA TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7412, 74, 'KABUPATEN KONAWE KEPULAUAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7413, 74, 'KABUPATEN MUNA BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7414, 74, 'KABUPATEN BUTON TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7415, 74, 'KABUPATEN BUTON SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7471, 74, 'KOTA KENDARI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7472, 74, 'KOTA BAUBAU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7501, 75, 'KABUPATEN BOALEMO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7502, 75, 'KABUPATEN GORONTALO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7503, 75, 'KABUPATEN POHUWATO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7504, 75, 'KABUPATEN BONE BOLANGO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7505, 75, 'KABUPATEN GORONTALO UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7571, 75, 'KOTA GORONTALO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7601, 76, 'KABUPATEN MAJENE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7602, 76, 'KABUPATEN POLEWALI MANDAR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7603, 76, 'KABUPATEN MAMASA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7604, 76, 'KABUPATEN MAMUJU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7605, 76, 'KABUPATEN MAMUJU UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (7606, 76, 'KABUPATEN MAMUJU TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8101, 81, 'KABUPATEN MALUKU TENGGARA BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8102, 81, 'KABUPATEN MALUKU TENGGARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8103, 81, 'KABUPATEN MALUKU TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8104, 81, 'KABUPATEN BURU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8105, 81, 'KABUPATEN KEPULAUAN ARU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8106, 81, 'KABUPATEN SERAM BAGIAN BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8107, 81, 'KABUPATEN SERAM BAGIAN TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8108, 81, 'KABUPATEN MALUKU BARAT DAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8109, 81, 'KABUPATEN BURU SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8171, 81, 'KOTA AMBON');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8172, 81, 'KOTA TUAL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8201, 82, 'KABUPATEN HALMAHERA BARAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8202, 82, 'KABUPATEN HALMAHERA TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8203, 82, 'KABUPATEN KEPULAUAN SULA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8204, 82, 'KABUPATEN HALMAHERA SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8205, 82, 'KABUPATEN HALMAHERA UTARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8206, 82, 'KABUPATEN HALMAHERA TIMUR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8207, 82, 'KABUPATEN PULAU MOROTAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8208, 82, 'KABUPATEN PULAU TALIABU');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8271, 82, 'KOTA TERNATE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (8272, 82, 'KOTA TIDORE KEPULAUAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9101, 91, 'KABUPATEN FAKFAK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9102, 91, 'KABUPATEN KAIMANA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9103, 91, 'KABUPATEN TELUK WONDAMA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9104, 91, 'KABUPATEN TELUK BINTUNI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9105, 91, 'KABUPATEN MANOKWARI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9106, 91, 'KABUPATEN SORONG SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9107, 91, 'KABUPATEN SORONG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9108, 91, 'KABUPATEN RAJA AMPAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9109, 91, 'KABUPATEN TAMBRAUW');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9110, 91, 'KABUPATEN MAYBRAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9111, 91, 'KABUPATEN MANOKWARI SELATAN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9112, 91, 'KABUPATEN PEGUNUNGAN ARFAK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9171, 91, 'KOTA SORONG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9401, 94, 'KABUPATEN MERAUKE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9402, 94, 'KABUPATEN JAYAWIJAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9403, 94, 'KABUPATEN JAYAPURA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9404, 94, 'KABUPATEN NABIRE');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9408, 94, 'KABUPATEN KEPULAUAN YAPEN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9409, 94, 'KABUPATEN BIAK NUMFOR');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9410, 94, 'KABUPATEN PANIAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9411, 94, 'KABUPATEN PUNCAK JAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9412, 94, 'KABUPATEN MIMIKA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9413, 94, 'KABUPATEN BOVEN DIGOEL');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9414, 94, 'KABUPATEN MAPPI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9415, 94, 'KABUPATEN ASMAT');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9416, 94, 'KABUPATEN YAHUKIMO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9417, 94, 'KABUPATEN PEGUNUNGAN BINTANG');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9418, 94, 'KABUPATEN TOLIKARA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9419, 94, 'KABUPATEN SARMI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9420, 94, 'KABUPATEN KEEROM');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9426, 94, 'KABUPATEN WAROPEN');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9427, 94, 'KABUPATEN SUPIORI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9428, 94, 'KABUPATEN MAMBERAMO RAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9429, 94, 'KABUPATEN NDUGA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9430, 94, 'KABUPATEN LANNY JAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9431, 94, 'KABUPATEN MAMBERAMO TENGAH');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9432, 94, 'KABUPATEN YALIMO');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9433, 94, 'KABUPATEN PUNCAK');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9434, 94, 'KABUPATEN DOGIYAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9435, 94, 'KABUPATEN INTAN JAYA');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9436, 94, 'KABUPATEN DEIYAI');
INSERT INTO m_kota_kab (id, id_propinsi, nama) VALUES (9471, 94, 'KOTA JAYAPURA');